import { FONT_FAMILIES, createMotion, createSpacing, createTypography } from "./foundations.js";
import type { ThemePack } from "./types.js";

export const MINIMAL_THEME: ThemePack = {
  id: "minimal",
  name: "Minimal",
  description: "A precise, gallery-like system where whitespace, alignment, and one indigo thread carry the explanation.",
  tags: ["quiet", "precise", "universal", "editorial"],
  intendedFor: ["concept explainers", "product walkthroughs", "executive summaries", "focused lessons"],
  palette: {
    canvas: "#F7F8FC", canvasAlt: "#EEF0F8", surface: "#FFFFFF", surfaceRaised: "#FFFFFF",
    ink: "#151827", inkMuted: "#4A5066", inkSubtle: "#626981", accent: "#5658E8",
    accentStrong: "#3436B8", accentSoft: "#E8E9FF", accentSecondary: "#7857A8", evidence: "#08756F",
    review: "#9C5706", critical: "#B93455", success: "#237047", line: "#D8DDEA", lineStrong: "#737B92",
    shadow: "#151827", onAccent: "#FFFFFF", captionBackground: "#151827", captionInk: "#FFFFFF",
    presenterMatte: "#E9EBF4", codeBackground: "#EDEFF7", codeInk: "#151827",
  },
  typography: createTypography({ display: FONT_FAMILIES.bricolage, heading: FONT_FAMILIES.bricolage, body: FONT_FAMILIES.atkinson, maxMeasureCh: 64 }),
  spacing: createSpacing("airy", { radiusSmall: 4, radiusMedium: 8, radiusLarge: 14, shadowBlur: 20 }),
  motion: createMotion("measured", { ambientMotion: "none", maxSimultaneousMotions: 3, staggerMs: 72 }),
  rules: {
    illustration: {
      mode: "geometric", geometry: "Use one clear primitive per concept; align all anchors to the concept-thread grid.",
      lineTreatment: "Hairlines are crisp and orthogonal; one heavier rule marks the active idea.",
      colorTreatment: "Mostly ink and paper, with indigo reserved for causality or current focus.",
      depthTreatment: "Near-flat; elevation appears only where interaction or hierarchy requires it.", texture: "No decorative texture; retain subtle optical anti-aliasing only.",
      subjectGuidance: "Prefer reduction, labeled silhouette, and scale contrast over literal stock imagery.", avoid: ["gratuitous gradients", "floating blobs", "decorative 3D objects", "dense icon fields"],
    },
    icons: { family: "outline", strokeWidth: 1.75, cornerStyle: "soft", container: "none", opticalSizePx: 24, usage: "Icons support labels; never replace an unfamiliar action label." },
    diagrams: { nodeShape: "rounded-rectangle", connector: "orthogonal", connectorWidth: 1.5, arrowStyle: "open", hierarchy: "Primary path is ink; the active concept is indigo; secondary paths recede.", annotation: "Short labels sit outside nodes on a shared baseline.", grid: "subtle", maximumColors: 4 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 42, widthPercent: 76, alignment: "center", treatment: "solid-panel", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "crossfade", section: "thread-wipe", emphasis: "cut", continuityDevice: "The concept thread advances between anchors without ornament.", avoid: ["spin", "bounce", "camera zoom", "direction changes without semantic cause"] },
    presenter: { framing: "waist-up", placement: "contextual", maximumSceneCoveragePercent: 32, backdrop: "matte", lowerThird: "minimal", entry: "Clean cut or six-frame opacity settle.", gestures: "Small, intentional gestures aligned with nearby callouts.", usage: "Hooks, misconception repair, and recaps only." },
  },
  visualBible: {
    thesis: "Make the learner feel that every element has a reason to exist.", audiencePromise: "A calm path through difficult material without visual noise.",
    signatureMotif: "A fine indigo concept thread links premises, evidence, and conclusions.",
    composition: ["Use asymmetric grids with one dominant focal area.", "Keep at least one quiet quadrant.", "Align evidence and annotations to the concept thread."],
    typographyHierarchy: ["Display type is short and structural.", "Body copy stays within 64 characters per line.", "Monospace appears only for exact values, code, and locators."],
    colorUsage: ["Indigo means active or causal.", "Teal means sourced evidence.", "Amber means review; rose means blocking failure."],
    imageTreatment: ["Crop to one unambiguous subject.", "Use neutral mats and factual captions.", "Never use an image when a diagram is more exact."],
    continuityRules: ["Preserve the concept-thread position across adjacent scenes.", "Carry one typographic anchor through section changes."],
    accessibilityRules: ["Never encode state by color alone.", "Hold labels long enough to read.", "Remove all ambient motion in reduced-motion mode."],
    noGo: ["glassmorphism", "admin-dashboard tiles", "AI sparkle motifs", "ornamental gradients", "unlabeled icons"],
  },
};

export const ACADEMIC_THEME: ThemePack = {
  id: "academic",
  name: "Academic",
  description: "A contemporary seminar-room language built from typeset argument, marginal evidence, and disciplined scholarly notation.",
  tags: ["scholarly", "serious", "evidence-led", "typeset"],
  intendedFor: ["university lectures", "research explainers", "mathematics", "document-grounded science"],
  palette: {
    canvas: "#F6F3EC", canvasAlt: "#EDE8DD", surface: "#FFFEFA", surfaceRaised: "#FFFFFF",
    ink: "#1D2428", inkMuted: "#4E585A", inkSubtle: "#677173", accent: "#355C7D",
    accentStrong: "#203E58", accentSoft: "#DFE9F0", accentSecondary: "#79513A", evidence: "#216A57",
    review: "#8B5A00", critical: "#A83A4A", success: "#356B3B", line: "#D5CEC0", lineStrong: "#817768",
    shadow: "#26231E", onAccent: "#FFFFFF", captionBackground: "#1D2428", captionInk: "#FFFFFF",
    presenterMatte: "#E7E1D5", codeBackground: "#EAE7DF", codeInk: "#1D2428",
  },
  typography: createTypography({ display: FONT_FAMILIES.sourceSerif, heading: FONT_FAMILIES.sourceSerif, body: FONT_FAMILIES.sourceSans, utility: FONT_FAMILIES.ibmPlex, displayWeight: 650, headingWeight: 620, maxMeasureCh: 72, sizes: { hero: 4.15, title: 2.55 } }),
  spacing: createSpacing("balanced", { radiusSmall: 2, radiusMedium: 4, radiusLarge: 8, borderWidth: 1, shadowBlur: 12 }),
  motion: createMotion("deliberate", { ambientMotion: "none", maxSimultaneousMotions: 3, staggerMs: 100 }),
  rules: {
    illustration: { mode: "editorial", geometry: "Use engraved cross-sections, measured plates, and carefully keyed figures.", lineTreatment: "Fine ink lines with variable weight and explicit figure labels.", colorTreatment: "Warm paper, blue argument, green evidence, and sparing umber context.", depthTreatment: "Layer like mounted paper figures, never glossy cards.", texture: "Subtle paper grain may appear at low contrast; text regions remain clean.", subjectGuidance: "Prefer primary diagrams, plots, scans, and annotated evidence over decorative illustration.", avoid: ["stock-photo metaphors", "neon color", "playful stickers", "fake handwriting"] },
    icons: { family: "technical", strokeWidth: 1.5, cornerStyle: "sharp", container: "label", opticalSizePx: 22, usage: "Use figure-style symbols with explicit text where ambiguity is possible." },
    diagrams: { nodeShape: "rectangle", connector: "straight", connectorWidth: 1.25, arrowStyle: "open", hierarchy: "Number figures and expose assumptions before conclusions.", annotation: "Margin notes use evidence locators, units, and concise qualifiers.", grid: "paper", maximumColors: 5 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 46, widthPercent: 80, alignment: "left", treatment: "document-label", speakerLabel: "when-needed", soundDescriptionStyle: "labelled" },
    transitions: { default: "cut", section: "page-turn", emphasis: "crossfade", continuityDevice: "Figure numbers and marginal citations persist as the argument develops.", avoid: ["whip pans", "elastic motion", "decorative parallax"] },
    presenter: { framing: "waist-up", placement: "right", maximumSceneCoveragePercent: 30, backdrop: "paper", lowerThird: "editorial", entry: "Enter on a paragraph or argument boundary.", gestures: "Measured pointing and open-hand emphasis; never loop gestures.", usage: "Frame the research question, qualify evidence, and summarize findings." },
  },
  visualBible: {
    thesis: "Treat every scene as a page in a rigorous visual argument.", audiencePromise: "Evidence, uncertainty, and reasoning remain visible rather than being flattened into claims.", signatureMotif: "Numbered marginalia connect each claim to its figure or source.",
    composition: ["Build around a central figure with a working margin.", "Expose units, scales, and labels.", "Reserve the bottom edge for citations and captioning."],
    typographyHierarchy: ["Serif display establishes argument and section changes.", "Sans body carries explanations and annotations.", "Math and code retain exact semantic glyphs."],
    colorUsage: ["Blue organizes argument.", "Green marks evidence.", "Umber adds historical or contextual layers."],
    imageTreatment: ["Retain provenance and figure labels.", "Never cosmetically crop away evidence context.", "Use document mats rather than card chrome."],
    continuityRules: ["Figure numbering never resets inside a lesson.", "Definitions retain the same marginal key when revisited."],
    accessibilityRules: ["Read equations in logical order.", "State uncertainty in narration and text.", "Provide text alternatives for every figure."],
    noGo: ["fake citations", "decorative equations", "uncaptioned figures", "paper texture behind small text", "ornamental Latin"],
  },
};

export const MODERN_TECH_THEME: ThemePack = {
  id: "modern-tech",
  name: "Modern Tech",
  description: "A luminous engineering interface with precise traces, signal accents, and code-first choreography—without cyberpunk clichés.",
  tags: ["technical", "luminous", "code", "systems"],
  intendedFor: ["software tutorials", "AI concepts", "systems architecture", "data engineering"],
  palette: {
    canvas: "#0D1320", canvasAlt: "#121B2C", surface: "#172238", surfaceRaised: "#1D2B45",
    ink: "#F4F7FB", inkMuted: "#B7C2D6", inkSubtle: "#92A1BA", accent: "#67E8D3",
    accentStrong: "#25BDAA", accentSoft: "#173E43", accentSecondary: "#9D8CFF", evidence: "#5CE1A6",
    review: "#FFC15B", critical: "#FF7894", success: "#66D49A", line: "#33425D", lineStrong: "#526581",
    shadow: "#02050A", onAccent: "#09221F", captionBackground: "#F4F7FB", captionInk: "#0D1320",
    presenterMatte: "#121D30", codeBackground: "#080D17", codeInk: "#EAF1FA",
  },
  typography: createTypography({ display: FONT_FAMILIES.bricolage, heading: FONT_FAMILIES.ibmPlex, body: FONT_FAMILIES.ibmPlex, utility: FONT_FAMILIES.jetbrains, displayWeight: 720, headingWeight: 620, utilityWeight: 550, maxMeasureCh: 66 }),
  spacing: createSpacing("balanced", { radiusSmall: 5, radiusMedium: 10, radiusLarge: 16, borderWidth: 1, shadowBlur: 32 }),
  motion: createMotion("lively", { ambientMotion: "subtle", maxSimultaneousMotions: 5, staggerMs: 58 }),
  rules: {
    illustration: { mode: "geometric", geometry: "Use traces, packets, bounded fields, and architecture layers tied to real system behavior.", lineTreatment: "Crisp 1–2px signal paths with luminous active segments, never fuzzy neon tubes.", colorTreatment: "Deep navy establishes space; mint tracks live state; violet separates model or abstraction layers.", depthTreatment: "Two functional depth planes with restrained inner highlights.", texture: "Very faint coordinate ticks or noise only in empty regions.", subjectGuidance: "Animate data flow, call stacks, dependency boundaries, and state changes rather than generic circuitry.", avoid: ["Matrix rain", "hacker clichés", "gratuitous holograms", "glowing every edge"] },
    icons: { family: "technical", strokeWidth: 1.6, cornerStyle: "soft", container: "rounded-square", opticalSizePx: 22, usage: "Icons act as stable system landmarks; pair new concepts with labels." },
    diagrams: { nodeShape: "rounded-rectangle", connector: "orthogonal", connectorWidth: 1.5, arrowStyle: "filled", hierarchy: "Active execution paths glow mint; latent paths remain slate; model boundaries use violet.", annotation: "Monospace state labels hug their owning edge or node.", grid: "subtle", maximumColors: 6 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 42, widthPercent: 78, alignment: "center", treatment: "soft-panel", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "thread-wipe", section: "dip-to-color", emphasis: "cut", continuityDevice: "A live signal trace carries state across scene boundaries.", avoid: ["random glitch", "scanline wipe", "constant zooming"] },
    presenter: { framing: "picture-in-picture", placement: "right", maximumSceneCoveragePercent: 24, backdrop: "soft-gradient", lowerThird: "minimal", entry: "Resolve from a system node at a natural pause.", gestures: "Point to active traces; avoid gesturing across code.", usage: "Orient the learner before a trace and return for debugging takeaways." },
  },
  visualBible: {
    thesis: "Turn invisible computation into a legible moving system.", audiencePromise: "The learner can always tell what is executing, changing, or waiting.", signatureMotif: "A mint signal trace moves through code, diagrams, and state panels.",
    composition: ["Use one dominant system plane and one supporting detail plane.", "Anchor code and trace state to a shared time cursor.", "Keep operational metadata compact and monospace."],
    typographyHierarchy: ["Display copy is assertive but brief.", "Technical headings are squared and stable.", "Code syntax never competes with the active trace."],
    colorUsage: ["Mint means active execution.", "Violet means abstraction or model state.", "Amber means pending review, not decoration."],
    imageTreatment: ["Prefer screen captures with focused crops.", "Place photos inside quiet, non-glowing mats.", "Never synthesize UI that could be mistaken for a real product."],
    continuityRules: ["Maintain signal direction across cuts.", "Preserve consistent colors for data, control, and model layers."],
    accessibilityRules: ["Pair all signal colors with line style or labels.", "Pause traces at narration landmarks.", "Disable glow pulsing and traveling signals under reduced motion."],
    noGo: ["cyberpunk wallpaper", "random hexadecimal decoration", "fake terminal output", "illegible tiny code", "persistent glitch effects"],
  },
};

export const NOTEBOOK_THEME: ThemePack = {
  id: "notebook",
  name: "Notebook",
  description: "A working-notebook aesthetic where ideas are assembled in view through honest marks, ruled structure, and tactile annotations.",
  tags: ["handmade", "worked-example", "approachable", "process"],
  intendedFor: ["worked examples", "study guides", "mathematics", "language learning"],
  palette: {
    canvas: "#FBF7ED", canvasAlt: "#F1EBDD", surface: "#FFFCF5", surfaceRaised: "#FFFFFF",
    ink: "#202631", inkMuted: "#515966", inkSubtle: "#69717B", accent: "#275DAD",
    accentStrong: "#174486", accentSoft: "#E0EAF8", accentSecondary: "#8B4A6D", evidence: "#27705C",
    review: "#945B00", critical: "#B13C4C", success: "#3E7040", line: "#D7D0C2", lineStrong: "#788293",
    shadow: "#29261F", onAccent: "#FFFFFF", captionBackground: "#202631", captionInk: "#FFFFFF",
    presenterMatte: "#EEE5D5", codeBackground: "#EDE9E0", codeInk: "#202631",
  },
  typography: createTypography({ display: FONT_FAMILIES.schoolbell, heading: FONT_FAMILIES.sourceSans, body: FONT_FAMILIES.atkinson, displayWeight: 700, headingWeight: 700, displayTracking: 0.005, headingTracking: -0.01, maxMeasureCh: 62, sizes: { hero: 4.35, title: 2.65 } }),
  spacing: createSpacing("balanced", { radiusSmall: 3, radiusMedium: 6, radiusLarge: 10, shadowBlur: 14 }),
  motion: createMotion("measured", { ambientMotion: "minimal", maxSimultaneousMotions: 4, staggerMs: 86 }),
  rules: {
    illustration: { mode: "hand-drawn", geometry: "Use disciplined hand-drawn arrows, boxes, underlines, and small explanatory sketches.", lineTreatment: "Marks vary subtly in pressure but remain deterministic and legible.", colorTreatment: "Blue ink for construction, berry for correction, green for verified results.", depthTreatment: "Paper slips may overlap by one shallow layer with soft contact shadows.", texture: "Light ruled or dot-grid paper; never place strong ruling behind dense copy.", subjectGuidance: "Reveal construction strokes in the same order a teacher would solve the problem.", avoid: ["messy doodle fields", "fake coffee stains", "illegible cursive", "random tape decoration"] },
    icons: { family: "hand-drawn", strokeWidth: 1.9, cornerStyle: "round", container: "none", opticalSizePx: 25, usage: "Use a small vocabulary of repeatable marks: check, question, pointer, and bookmark." },
    diagrams: { nodeShape: "mixed", connector: "hand-drawn", connectorWidth: 1.7, arrowStyle: "open", hierarchy: "Construction is blue; correction is berry; verified result is green and double-underlined.", annotation: "Notes sit in margins with short leader lines.", grid: "paper", maximumColors: 5 },
    captions: { position: "lower-third", maxLines: 2, maxCharactersPerLine: 40, widthPercent: 74, alignment: "left", treatment: "document-label", speakerLabel: "when-needed", soundDescriptionStyle: "italic" },
    transitions: { default: "crossfade", section: "page-turn", emphasis: "thread-wipe", continuityDevice: "A drawn underline extends into the next working step.", avoid: ["rapid page flipping", "paper scraps covering content", "scribble reveals over narration"] },
    presenter: { framing: "cutout", placement: "left", maximumSceneCoveragePercent: 28, backdrop: "paper", lowerThird: "minimal", entry: "Appear as a margin guide beside the working area.", gestures: "Trace the next operation; keep hands clear of equations.", usage: "Set up examples, voice misconceptions, and validate the final method." },
  },
  visualBible: {
    thesis: "Let the learner watch understanding being constructed, not merely presented.", audiencePromise: "Every correction and intermediate step remains visible and purposeful.", signatureMotif: "A blue working underline grows into arrows, brackets, and conclusion marks.",
    composition: ["Treat the scene as a clean notebook spread with an active working column.", "Keep permanent givens separate from changing work.", "Use margins for questions and evidence."],
    typographyHierarchy: ["Hand lettering appears only in short display moments.", "Long explanations use high-legibility sans.", "Exact symbols remain typeset, never hand-simulated."],
    colorUsage: ["Blue is working logic.", "Berry identifies corrections or misconceptions.", "Green marks checked outcomes."],
    imageTreatment: ["Mount images like reference clippings with source labels.", "Keep edges square and crops factual.", "Avoid sentimental scrapbook treatments."],
    continuityRules: ["Never erase a needed intermediate result.", "Carry key variables and color assignments between steps."],
    accessibilityRules: ["Narrate handwritten marks as they appear.", "Keep ruling below minimum contrast around body text.", "Use shape and wording in addition to ink color."],
    noGo: ["fake student mess", "decorative cursive paragraphs", "coffee-ring nostalgia", "washi-tape clutter", "unexplained correction marks"],
  },
};

export const DOCUMENTARY_THEME: ThemePack = {
  id: "documentary",
  name: "Documentary",
  description: "An evidence-forward cinematic system for real people, places, records, and chronology, grounded by source slates and restrained motion.",
  tags: ["cinematic", "historical", "photographic", "evidence"],
  intendedFor: ["history", "case studies", "biographies", "investigations", "field science"],
  palette: {
    canvas: "#151716", canvasAlt: "#20221F", surface: "#252823", surfaceRaised: "#30332E",
    ink: "#F3F0E8", inkMuted: "#C4C0B5", inkSubtle: "#9F9B91", accent: "#D7A84B",
    accentStrong: "#F0C76E", accentSoft: "#423821", accentSecondary: "#78A5AA", evidence: "#74B9A5",
    review: "#E2B45D", critical: "#F07C78", success: "#8ECA8A", line: "#45483F", lineStrong: "#686B60",
    shadow: "#050605", onAccent: "#241A08", captionBackground: "#F3F0E8", captionInk: "#151716",
    presenterMatte: "#22251F", codeBackground: "#0E100F", codeInk: "#EEEAE0",
  },
  typography: createTypography({ display: FONT_FAMILIES.fraunces, heading: FONT_FAMILIES.sourceSerif, body: FONT_FAMILIES.sourceSans, utility: FONT_FAMILIES.ibmPlex, displayWeight: 650, headingWeight: 620, displayTracking: -0.02, maxMeasureCh: 70, sizes: { hero: 4.65, title: 2.8 } }),
  spacing: createSpacing("airy", { radiusSmall: 0, radiusMedium: 2, radiusLarge: 4, shadowBlur: 30 }),
  motion: createMotion("deliberate", { ambientMotion: "subtle", maxSimultaneousMotions: 3, staggerMs: 110 }),
  rules: {
    illustration: { mode: "photographic", geometry: "Use real aspect ratios, maps, timelines, archival documents, and restrained locator graphics.", lineTreatment: "Rules are thin and editorial; source frames use a heavier bottom keyline.", colorTreatment: "Warm monochrome may unify mixed evidence, but original color is preserved when materially relevant.", depthTreatment: "Photographs occupy a clear image plane; captions and source slates sit above, never inside ambiguous overlays.", texture: "Film grain is optional, subtle, and prohibited over text or diagrams.", subjectGuidance: "Favor verified records and licensed imagery; label reconstructions and generated material visibly.", avoid: ["fake archival damage", "generic dramatic stock", "unlabeled reenactment", "constant Ken Burns motion"] },
    icons: { family: "solid", strokeWidth: 1.5, cornerStyle: "sharp", container: "label", opticalSizePx: 20, usage: "Use sparingly for media type, location, date, and evidence status." },
    diagrams: { nodeShape: "rectangle", connector: "straight", connectorWidth: 1.25, arrowStyle: "dot", hierarchy: "Dates and places anchor the spine; testimony and artifacts branch with explicit source status.", annotation: "Source, date, location, and rights appear in concise slates.", grid: "none", maximumColors: 5 },
    captions: { position: "lower-third", maxLines: 2, maxCharactersPerLine: 44, widthPercent: 82, alignment: "left", treatment: "solid-panel", speakerLabel: "always", soundDescriptionStyle: "labelled" },
    transitions: { default: "cut", section: "dip-to-color", emphasis: "crossfade", continuityDevice: "A dated evidence slate or map locator bridges time and place.", avoid: ["film-burn transitions", "shutter effects", "sensational zooms"] },
    presenter: { framing: "head-and-shoulders", placement: "left", maximumSceneCoveragePercent: 34, backdrop: "environmental", lowerThird: "editorial", entry: "Enter by motivated cut after the evidence establishing shot.", gestures: "Natural, restrained, and never composited over primary evidence.", usage: "Provide context, distinguish interpretation from fact, and close sections." },
  },
  visualBible: {
    thesis: "Let evidence establish reality before interpretation asks for attention.", audiencePromise: "The learner can distinguish record, reconstruction, and analysis at a glance.", signatureMotif: "A compact source slate carries date, place, provenance, and evidence status.",
    composition: ["Begin sequences with place, object, or document before commentary.", "Give primary evidence the largest uninterrupted area.", "Keep chronology on a stable spatial spine."],
    typographyHierarchy: ["Display serif frames chapters, not every fact.", "Utility labels handle provenance and chronology.", "Quotes retain speaker, date, and source context."],
    colorUsage: ["Gold marks chronology and focus.", "Teal marks corroborated evidence.", "Rose identifies contradiction or unresolved risk."],
    imageTreatment: ["Preserve context and credit.", "Label generated reconstructions on-frame.", "Avoid aggressive crops that alter meaning."],
    continuityRules: ["Maintain direction of time and geography.", "Repeat source status consistently whenever evidence returns."],
    accessibilityRules: ["Describe visual evidence, not just mood.", "Caption speakers and meaningful sounds.", "Avoid flashes and rapid montage."],
    noGo: ["sensational true-crime styling", "fake film borders", "uncredited media", "dramatic music by default", "presenter covering evidence"],
  },
};

export const PLAYFUL_THEME: ThemePack = {
  id: "playful",
  name: "Playful",
  description: "A spirited modular world of elastic shapes and friendly visual jokes, disciplined enough to keep the lesson in charge.",
  tags: ["energetic", "friendly", "colorful", "modular"],
  intendedFor: ["general explainers", "onboarding", "creative skills", "teen learning"],
  palette: {
    canvas: "#FFF8F0", canvasAlt: "#FCEBD9", surface: "#FFFFFF", surfaceRaised: "#FFFFFF",
    ink: "#24213A", inkMuted: "#55516C", inkSubtle: "#6D687F", accent: "#6C50D8",
    accentStrong: "#4C33AF", accentSoft: "#EDE7FF", accentSecondary: "#D64E72", evidence: "#08776F",
    review: "#9A5A00", critical: "#B93658", success: "#34713E", line: "#DDD4E6", lineStrong: "#837693",
    shadow: "#30274A", onAccent: "#FFFFFF", captionBackground: "#24213A", captionInk: "#FFFFFF",
    presenterMatte: "#F2E5FF", codeBackground: "#EEEAF5", codeInk: "#24213A",
  },
  typography: createTypography({ display: FONT_FAMILIES.bricolage, heading: FONT_FAMILIES.nunito, body: FONT_FAMILIES.nunito, utility: FONT_FAMILIES.lexend, displayWeight: 760, headingWeight: 750, bodyWeight: 500, displayTracking: -0.028, maxMeasureCh: 60, sizes: { hero: 4.8, title: 2.9, heading: 1.65 } }),
  spacing: createSpacing("balanced", { radiusSmall: 8, radiusMedium: 16, radiusLarge: 28, shadowBlur: 24 }),
  motion: createMotion("energetic", { ambientMotion: "subtle", maxSimultaneousMotions: 5, staggerMs: 48, easing: { emphasis: "cubic-bezier(0.18, 1.55, 0.42, 1)" } }),
  rules: {
    illustration: { mode: "geometric", geometry: "Build concepts from chunky modules, cut-paper arcs, and one surprising scale shift per scene.", lineTreatment: "Rounded outlines vary between 2px structural marks and 4px emphasis marks.", colorTreatment: "Purple organizes the lesson; coral adds human emphasis; teal confirms evidence.", depthTreatment: "Two paper-like layers with decisive offset shadows, never translucent glass.", texture: "Subtle speckle may live inside large shapes, away from text.", subjectGuidance: "Use visual wit to clarify relationships, not as unrelated mascot activity.", avoid: ["rainbow overload", "confetti on every success", "wobbly body copy", "sticker clutter"] },
    icons: { family: "duotone", strokeWidth: 2, cornerStyle: "round", container: "circle", opticalSizePx: 26, usage: "Assign stable icon characters to repeated learning actions, with labels on first use." },
    diagrams: { nodeShape: "capsule", connector: "curved", connectorWidth: 2, arrowStyle: "filled", hierarchy: "Size expresses importance; hue separates roles; active connections subtly stretch toward the destination.", annotation: "Use short conversational notes in small offset labels.", grid: "none", maximumColors: 6 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 38, widthPercent: 74, alignment: "center", treatment: "speech-card", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "push", section: "thread-wipe", emphasis: "iris", continuityDevice: "The active module reshapes into the opening form of the next scene.", avoid: ["continuous bouncing", "random rotations", "confetti transitions"] },
    presenter: { framing: "cutout", placement: "alternating", maximumSceneCoveragePercent: 30, backdrop: "soft-gradient", lowerThird: "playful", entry: "Pop from behind a meaningful shape with a quick settle.", gestures: "Warm, clear, and synchronized to one nearby visual beat.", usage: "Hooks, encouragement after effort, misconceptions, and recap challenges." },
  },
  visualBible: {
    thesis: "Use delight as a teaching rhythm, never as a substitute for explanation.", audiencePromise: "Complex ideas feel inviting, active, and possible without becoming childish.", signatureMotif: "A modular purple shape changes form as the learner advances.",
    composition: ["Use one oversized teaching shape and two supporting elements.", "Keep copy on quiet paper fields.", "Let scale changes correspond to conceptual importance."],
    typographyHierarchy: ["Display type may flex in size, not distort in shape.", "Body type stays stable and highly legible.", "Utility labels are compact and reassuring."],
    colorUsage: ["Purple marks structure.", "Coral marks a human prompt or misconception.", "Teal marks grounded evidence or completion."],
    imageTreatment: ["Use clean cutouts with a deliberate shadow language.", "Integrate photos into the modular composition.", "Never cover faces or evidence with decoration."],
    continuityRules: ["Reuse shape identities for recurring concepts.", "Carry one motion vector through each transition."],
    accessibilityRules: ["Meaning survives in grayscale.", "No essential information moves continuously.", "Reduced motion swaps shape travel for a clean dissolve."],
    noGo: ["gamified reward spam", "emoji as primary iconography", "random blob backgrounds", "squiggly paragraph text", "unmotivated sound cues"],
  },
};

export const CHILDRENS_EDUCATION_THEME: ThemePack = {
  id: "childrens-education",
  name: "Children's Education",
  description: "A storybook learning world with kind character guidance, large readable forms, and predictable rhythms for younger learners.",
  tags: ["children", "storybook", "character-led", "high-legibility"],
  intendedFor: ["primary education", "family learning", "early literacy", "child-friendly science"],
  palette: {
    canvas: "#FFF9E8", canvasAlt: "#F3EED5", surface: "#FFFFFF", surfaceRaised: "#FFFFFF",
    ink: "#26334A", inkMuted: "#4F5B70", inkSubtle: "#667286", accent: "#375EBA",
    accentStrong: "#244797", accentSoft: "#E1EAFF", accentSecondary: "#A4447D", evidence: "#167064",
    review: "#8D5A00", critical: "#AC3D50", success: "#3E7039", line: "#D9D5C2", lineStrong: "#77828F",
    shadow: "#2D3850", onAccent: "#FFFFFF", captionBackground: "#26334A", captionInk: "#FFFFFF",
    presenterMatte: "#E9F0FF", codeBackground: "#EDF0E7", codeInk: "#26334A",
  },
  typography: createTypography({ display: FONT_FAMILIES.lexend, heading: FONT_FAMILIES.lexend, body: FONT_FAMILIES.atkinson, utility: FONT_FAMILIES.lexend, displayWeight: 720, headingWeight: 700, bodyWeight: 500, displayTracking: -0.02, headingTracking: -0.008, maxMeasureCh: 50, sizes: { hero: 4.65, title: 2.8, heading: 1.7, body: 1.08, caption: 1.1 } }),
  spacing: createSpacing("airy", { safeAreaPercent: 6, radiusSmall: 10, radiusMedium: 18, radiusLarge: 30, shadowBlur: 18, contentGap: 34 }),
  motion: createMotion("lively", { ambientMotion: "minimal", maxSimultaneousMotions: 3, staggerMs: 90, durationMs: { standard: 440, slow: 700 } }),
  rules: {
    illustration: { mode: "character-led", geometry: "Use large soft silhouettes, simple expressions, and environments with three clear depth bands.", lineTreatment: "Dark blue outlines remain consistent and thick enough for small screens.", colorTreatment: "Warm paper supports focused blue, berry, and green characters; limit each scene to one dominant accent.", depthTreatment: "Layer like a modern picture book with gentle contact shadows.", texture: "Soft crayon or grain may enrich large fills but stays out of letterforms.", subjectGuidance: "Characters model curiosity, effort, and correction; they never solve the task instead of the learner.", avoid: ["babyish clip art", "hyperactive mascots", "scary expressions", "gender-coded role colors"] },
    icons: { family: "solid", strokeWidth: 2.25, cornerStyle: "round", container: "rounded-square", opticalSizePx: 30, usage: "Use concrete, culturally neutral objects with spoken and written labels." },
    diagrams: { nodeShape: "circle", connector: "curved", connectorWidth: 2.5, arrowStyle: "filled", hierarchy: "One relationship appears at a time; prior nodes remain visible but quiet.", annotation: "Use plain-language labels of five words or fewer near the object they explain.", grid: "none", maximumColors: 5 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 32, widthPercent: 82, alignment: "center", treatment: "speech-card", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "crossfade", section: "page-turn", emphasis: "iris", continuityDevice: "A guide character looks or points toward the next learning object.", avoid: ["surprise flashes", "fast spins", "objects flying at the viewer"] },
    presenter: { framing: "full-body", placement: "contextual", maximumSceneCoveragePercent: 26, backdrop: "transparent", lowerThird: "playful", entry: "Walk or peek in from the side that keeps the reading path clear.", gestures: "Model the action slowly, pause, then invite the learner to try.", usage: "Welcome, model effort, ask questions, normalize mistakes, and celebrate specific learning." },
  },
  visualBible: {
    thesis: "Create a safe story rhythm in which curiosity leads, effort is visible, and mistakes become useful.", audiencePromise: "Young learners always know where to look, what to try, and why it matters.", signatureMotif: "A friendly path of stepping stones records each idea mastered.",
    composition: ["One learning object dominates each scene.", "Keep characters beside—not on top of—the work.", "Use predictable left-to-right or locale-correct progress paths."],
    typographyHierarchy: ["Words use familiar letterforms and generous spacing.", "Instructions stay short and direct.", "New vocabulary appears with object, sound, and definition together."],
    colorUsage: ["Blue guides attention.", "Berry asks a question or signals a misconception.", "Green confirms a checked answer."],
    imageTreatment: ["Favor inclusive, specific depictions over generic child stock.", "Keep expressions clear at thumbnail size.", "Represent diverse bodies, families, and cultures without tokenism."],
    continuityRules: ["Guide characters retain stable colors and roles.", "Repeat instructions in the same visual location.", "Return to the stepping-stone path at section boundaries."],
    accessibilityRules: ["Use plain language and concrete verbs.", "Never rely on rapid timing for success.", "Provide narration, captions, and descriptive alternatives."],
    noGo: ["reward explosions", "shaming wrong answers", "tiny copy", "stereotyped characters", "busy patterned text backgrounds"],
  },
};

export const CORPORATE_TRAINING_THEME: ThemePack = {
  id: "corporate-training",
  name: "Corporate Training",
  description: "A clear operational system for procedures, policy, compliance, and workplace learning, with restrained authority and practical examples.",
  tags: ["professional", "procedural", "compliance", "scalable"],
  intendedFor: ["employee onboarding", "compliance", "software rollout", "leadership training"],
  palette: {
    canvas: "#F3F6F8", canvasAlt: "#E8EEF2", surface: "#FFFFFF", surfaceRaised: "#FFFFFF",
    ink: "#172A38", inkMuted: "#495C68", inkSubtle: "#60727C", accent: "#176B8C",
    accentStrong: "#0D506D", accentSoft: "#DCECF2", accentSecondary: "#6953A8", evidence: "#14705D",
    review: "#8C5A00", critical: "#A9384E", success: "#2E6F43", line: "#D1DCE2", lineStrong: "#738690",
    shadow: "#172A38", onAccent: "#FFFFFF", captionBackground: "#172A38", captionInk: "#FFFFFF",
    presenterMatte: "#E1EAF0", codeBackground: "#E8EEF2", codeInk: "#172A38",
  },
  typography: createTypography({ display: FONT_FAMILIES.ibmPlex, heading: FONT_FAMILIES.ibmPlex, body: FONT_FAMILIES.sourceSans, utility: FONT_FAMILIES.ibmPlex, displayWeight: 680, headingWeight: 650, bodyWeight: 450, maxMeasureCh: 70, sizes: { hero: 4.1, title: 2.5, heading: 1.48 } }),
  spacing: createSpacing("compact", { radiusSmall: 3, radiusMedium: 6, radiusLarge: 10, shadowBlur: 18, contentGap: 24 }),
  motion: createMotion("measured", { ambientMotion: "none", maxSimultaneousMotions: 3, staggerMs: 72 }),
  rules: {
    illustration: { mode: "line", geometry: "Use clean workplace scenarios, process lanes, decision trees, and interface close-ups.", lineTreatment: "Consistent technical outlines with filled emphasis only for the current action.", colorTreatment: "Blue organizes procedures; green confirms compliant action; violet separates coaching or reflection.", depthTreatment: "Flat operational planes with a single elevation step for active tasks.", texture: "No texture behind operational content; use subtle neutral photography only when context matters.", subjectGuidance: "Show realistic decisions and consequences without depicting branded systems inaccurately.", avoid: ["handshake stock photos", "generic office towers", "excessive badges", "motivational poster imagery"] },
    icons: { family: "outline", strokeWidth: 1.75, cornerStyle: "soft", container: "rounded-square", opticalSizePx: 23, usage: "Use a governed icon vocabulary for actions, policy, people, systems, and risk." },
    diagrams: { nodeShape: "rounded-rectangle", connector: "orthogonal", connectorWidth: 1.5, arrowStyle: "filled", hierarchy: "Number sequential actions; use explicit yes/no branches; show owners and outcomes.", annotation: "Action labels start with verbs; policy references appear in a quiet footer.", grid: "subtle", maximumColors: 5 },
    captions: { position: "bottom-safe", maxLines: 2, maxCharactersPerLine: 44, widthPercent: 80, alignment: "center", treatment: "solid-panel", speakerLabel: "when-needed", soundDescriptionStyle: "labelled" },
    transitions: { default: "cut", section: "thread-wipe", emphasis: "crossfade", continuityDevice: "A numbered action rail advances through the procedure.", avoid: ["decorative wipes", "celebration bursts", "unmotivated camera moves"] },
    presenter: { framing: "waist-up", placement: "right", maximumSceneCoveragePercent: 30, backdrop: "matte", lowerThird: "corporate", entry: "Clean cut at a coaching, policy, or reflection beat.", gestures: "Direct, warm, and limited to the current action or consequence.", usage: "Welcome, contextualize policy, model difficult conversations, and summarize next actions." },
  },
  visualBible: {
    thesis: "Translate policy into clear decisions people can recognize and act on.", audiencePromise: "The learner leaves knowing the correct action, owner, and escalation path.", signatureMotif: "A numbered action rail links context, decision, action, and outcome.",
    composition: ["Place context on the left and action on the right.", "Show one decision point at a time.", "Keep policy citations and ownership visible but secondary."],
    typographyHierarchy: ["Headings name an operational outcome.", "Instructions begin with verbs.", "Policy identifiers use compact utility type."],
    colorUsage: ["Blue marks the active procedure.", "Green marks a compliant verified outcome.", "Rose marks prohibited action or escalation risk."],
    imageTreatment: ["Use specific workplace contexts, not aspiration imagery.", "Protect privacy in interface captures.", "Label reenactments and synthetic presenters."],
    continuityRules: ["Action numbers and ownership persist across scenarios.", "Keep risk and escalation semantics consistent."],
    accessibilityRules: ["Use plain language and explain acronyms.", "Offer transcript and keyboard-accessible practice.", "Do not make passing depend on speed."],
    noGo: ["generic business stock", "gratuitous KPIs", "management-dashboard chrome", "vague calls to action", "celebrating compliance with confetti"],
  },
};

export const LIGHT_THEME: ThemePack = {
  id: "light",
  name: "Light",
  description: "A versatile bright studio default with crisp hierarchy, gentle depth, and the Alystria concept thread as its organizing spine.",
  tags: ["default", "bright", "versatile", "studio"],
  intendedFor: ["mixed-format tutorials", "product education", "science", "general learning"],
  palette: {
    canvas: "#F7F8FC", canvasAlt: "#ECEFFA", surface: "#FFFFFF", surfaceRaised: "#FFFFFF",
    ink: "#151827", inkMuted: "#495067", inkSubtle: "#626A81", accent: "#5658E8",
    accentStrong: "#3739BD", accentSoft: "#E7E8FF", accentSecondary: "#8A4E9A", evidence: "#168077",
    review: "#965600", critical: "#B83B5C", success: "#277044", line: "#D8DDEA", lineStrong: "#747D94",
    shadow: "#171B30", onAccent: "#FFFFFF", captionBackground: "#151827", captionInk: "#FFFFFF",
    presenterMatte: "#E8EAF5", codeBackground: "#ECEEF7", codeInk: "#151827",
  },
  typography: createTypography({ display: FONT_FAMILIES.bricolage, heading: FONT_FAMILIES.bricolage, body: FONT_FAMILIES.atkinson, utility: FONT_FAMILIES.atkinson, displayWeight: 720, headingWeight: 660, maxMeasureCh: 68 }),
  spacing: createSpacing("balanced", { radiusSmall: 6, radiusMedium: 12, radiusLarge: 20, shadowBlur: 24 }),
  motion: createMotion("measured", { ambientMotion: "minimal", maxSimultaneousMotions: 4, staggerMs: 68 }),
  rules: {
    illustration: { mode: "editorial", geometry: "Mix exact diagrams with clean editorial cutouts, all anchored to the same concept-thread grid.", lineTreatment: "Crisp ink outlines with indigo active segments and occasional filled focus planes.", colorTreatment: "Studio paper dominates; indigo guides; teal certifies evidence; berry is reserved for human nuance.", depthTreatment: "Shallow, purposeful layers with soft contact shadows.", texture: "Low-noise paper and subtle illustration grain are allowed away from text.", subjectGuidance: "Choose the most exact visual form first, then add warmth through crop, scale, or illustration character.", avoid: ["generic gradients", "floating dashboard cards", "glossy 3D icons", "unstructured collage"] },
    icons: { family: "duotone", strokeWidth: 1.75, cornerStyle: "soft", container: "rounded-square", opticalSizePx: 24, usage: "Icons reinforce known actions and scene categories, with text for unfamiliar concepts." },
    diagrams: { nodeShape: "rounded-rectangle", connector: "curved", connectorWidth: 1.6, arrowStyle: "filled", hierarchy: "Indigo carries the main reasoning path; evidence attaches in teal; annotations stay ink-muted.", annotation: "Short labels align to a stable outer rail.", grid: "subtle", maximumColors: 6 },
    captions: { position: "adaptive", maxLines: 2, maxCharactersPerLine: 42, widthPercent: 78, alignment: "center", treatment: "solid-panel", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "thread-wipe", section: "crossfade", emphasis: "cut", continuityDevice: "The Alystria concept thread bends toward the next active idea.", avoid: ["template slideshow wipes", "random direction changes", "constant scaling"] },
    presenter: { framing: "waist-up", placement: "contextual", maximumSceneCoveragePercent: 30, backdrop: "soft-gradient", lowerThird: "minimal", entry: "Emerge beside the concept thread after the scene establishes its subject.", gestures: "Point along the reasoning path and yield space before dense visuals.", usage: "Sparse by default: hooks, transitions, empathy, misconceptions, and recaps." },
  },
  visualBible: {
    thesis: "Create a bright precision studio where evidence and ideas visibly connect.", audiencePromise: "A polished tutorial that feels authored, coherent, and easy to navigate.", signatureMotif: "A restrained indigo concept thread links objectives, scenes, citations, and review marks.",
    composition: ["Use one primary visual field and one evidence or annotation rail.", "Keep a clean safe area around captions.", "Let the thread reveal structure rather than decorate empty space."],
    typographyHierarchy: ["Bricolage supplies restrained character to titles.", "Atkinson carries sustained reading.", "JetBrains Mono identifies exact technical material."],
    colorUsage: ["Indigo means current concept or action.", "Teal means evidence or verified state.", "Amber means review; rose means blocking issue."],
    imageTreatment: ["Use factual crops with source context.", "Blend generated illustration through shared line and grain treatment.", "Never place text over high-detail imagery without an opaque reading surface."],
    continuityRules: ["The concept thread preserves semantic position across scenes.", "Recurring concepts keep stable color and typographic treatment."],
    accessibilityRules: ["All semantic colors have icons or labels.", "Captions adapt away from essential visuals.", "Reduced motion preserves continuity through crossfades."],
    noGo: ["glassmorphism", "AI chat-wrapper composition", "unearned gradients", "emoji headings", "decorative data"],
  },
};

export const DARK_THEME: ThemePack = {
  id: "dark",
  name: "Dark",
  description: "A calm dark-room studio for sustained focus, with luminous evidence accents and high-fidelity media presentation.",
  tags: ["default", "dark", "focused", "cinematic"],
  intendedFor: ["coding", "screen demonstrations", "cinematic explainers", "low-light viewing"],
  palette: {
    canvas: "#11131B", canvasAlt: "#181B27", surface: "#1D2130", surfaceRaised: "#252A3C",
    ink: "#F5F6FA", inkMuted: "#BDC2D1", inkSubtle: "#969DAF", accent: "#A9A8FF",
    accentStrong: "#C6C5FF", accentSoft: "#34345D", accentSecondary: "#E69BC3", evidence: "#66D2C5",
    review: "#F0B85E", critical: "#FF819D", success: "#7BD59D", line: "#383E54", lineStrong: "#59617B",
    shadow: "#030409", onAccent: "#17172A", captionBackground: "#F5F6FA", captionInk: "#11131B",
    presenterMatte: "#191D2A", codeBackground: "#090B11", codeInk: "#EEF0F7",
  },
  typography: createTypography({ display: FONT_FAMILIES.bricolage, heading: FONT_FAMILIES.bricolage, body: FONT_FAMILIES.atkinson, utility: FONT_FAMILIES.atkinson, displayWeight: 700, headingWeight: 640, maxMeasureCh: 68 }),
  spacing: createSpacing("balanced", { radiusSmall: 6, radiusMedium: 12, radiusLarge: 20, shadowBlur: 34 }),
  motion: createMotion("measured", { ambientMotion: "minimal", maxSimultaneousMotions: 4, staggerMs: 72 }),
  rules: {
    illustration: { mode: "editorial", geometry: "Use strong silhouettes, isolated evidence planes, and a stable luminous thread against deep neutral space.", lineTreatment: "Fine cool-gray structure with lavender active edges and teal evidence keys.", colorTreatment: "Keep most of the frame neutral; luminous accents are semantic and localized.", depthTreatment: "Three quiet planes separated by value, not glass blur.", texture: "Subtle dither or grain may prevent banding in empty dark regions; exclude text and diagrams.", subjectGuidance: "Give screenshots, code, and footage enough unbroken space to remain faithful.", avoid: ["pure black expanses", "neon everywhere", "glowing paragraph text", "cyberpunk decoration"] },
    icons: { family: "duotone", strokeWidth: 1.65, cornerStyle: "soft", container: "rounded-square", opticalSizePx: 24, usage: "Use cool-gray structure and one semantic accent; avoid rainbow icon sets." },
    diagrams: { nodeShape: "rounded-rectangle", connector: "curved", connectorWidth: 1.6, arrowStyle: "filled", hierarchy: "Lavender marks active reasoning; teal marks evidence; inactive structure remains cool gray.", annotation: "Annotations sit on opaque dark fields with generous spacing.", grid: "subtle", maximumColors: 5 },
    captions: { position: "adaptive", maxLines: 2, maxCharactersPerLine: 42, widthPercent: 78, alignment: "center", treatment: "solid-panel", speakerLabel: "when-needed", soundDescriptionStyle: "bracketed" },
    transitions: { default: "thread-wipe", section: "dip-to-color", emphasis: "cut", continuityDevice: "A localized lavender thread redraws only the semantic path that changes.", avoid: ["full-frame flashes", "neon glitch", "high-speed tunnel motion"] },
    presenter: { framing: "waist-up", placement: "contextual", maximumSceneCoveragePercent: 30, backdrop: "matte", lowerThird: "minimal", entry: "Fade up from the matte after the content plane settles.", gestures: "Contained gestures with a clear silhouette, never over bright content.", usage: "Sparse: opening orientation, misconception repair, section bridges, and final synthesis." },
  },
  visualBible: {
    thesis: "Use darkness as quiet working space, then illuminate only the idea that matters now.", audiencePromise: "Long, technical lessons remain comfortable and visually exact.", signatureMotif: "A lavender concept thread appears as a precise edge light through the lesson.",
    composition: ["Keep a stable dark field around the focal plane.", "Separate depth by luminance before shadow.", "Reserve bright white for text and critical media detail."],
    typographyHierarchy: ["Display type is restrained and bright, never glowing.", "Body text uses softened white for sustained reading.", "Code uses a deeper matte with balanced syntax color."],
    colorUsage: ["Lavender marks active structure.", "Teal marks evidence.", "Amber and rose are reserved for review and risk."],
    imageTreatment: ["Preserve source color unless grading has an instructional reason.", "Use neutral dark mats around mismatched aspect ratios.", "Avoid vignettes that hide evidence."],
    continuityRules: ["Keep focal luminance stable across cuts.", "Preserve the concept-thread edge and motion direction."],
    accessibilityRules: ["Avoid pure-white large fields that flash between scenes.", "Ensure subdued text still passes contrast.", "Reduced motion uses luminance-safe dissolves."],
    noGo: ["pure black on pure white flashes", "neon cyberpunk tropes", "transparent glass panels", "low-contrast gray text", "glow around captions"],
  },
};

export const BUILT_IN_THEME_PACKS: readonly ThemePack[] = Object.freeze([
  MINIMAL_THEME,
  ACADEMIC_THEME,
  MODERN_TECH_THEME,
  NOTEBOOK_THEME,
  DOCUMENTARY_THEME,
  PLAYFUL_THEME,
  CHILDRENS_EDUCATION_THEME,
  CORPORATE_TRAINING_THEME,
  LIGHT_THEME,
  DARK_THEME,
]);
