"""Alystria's durable staged tutorial-generation coordinator."""

from .adapters import (
    DeterministicMediaClient,
    DeterministicRendererClient,
    GeneratedMedia,
    GenerationMediaClient,
    RenderedTutorial,
    RendererClient,
    RouterMediaClient,
    RuntimeGenerationMediaClient,
    WindowsFallbackMediaClient,
    WindowsNarrationAdapter,
    default_local_media_client,
)
from .coordinator import (
    ApprovalNotReadyError,
    GenerationCoordinator,
    GenerationNotFoundError,
    request_from_desktop,
    request_from_fixture,
)
from .models import (
    ALL_STAGES,
    ClaimSpec,
    GenerationRequest,
    GenerationStage,
    GenerationState,
    GenerationStatus,
    ObjectiveSpec,
    SourceSpec,
    StageStatus,
)
from .renderer_client import (
    CommandResult,
    PinnedExecutable,
    RendererCancelledError,
    RendererClientError,
    RendererCommandRunner,
    RendererOptions,
    RendererOutputError,
    RendererRuntimeError,
    RendererRuntimePins,
    RendererTimeoutError,
    SubprocessCommandRunner,
    SubprocessRendererClient,
    create_production_renderer_client,
)
from .workflow import GenerationWorkflow

__all__ = [
    "ALL_STAGES",
    "ApprovalNotReadyError",
    "ClaimSpec",
    "CommandResult",
    "DeterministicMediaClient",
    "DeterministicRendererClient",
    "GeneratedMedia",
    "GenerationCoordinator",
    "GenerationMediaClient",
    "GenerationNotFoundError",
    "GenerationRequest",
    "GenerationStage",
    "GenerationState",
    "GenerationStatus",
    "GenerationWorkflow",
    "ObjectiveSpec",
    "PinnedExecutable",
    "RenderedTutorial",
    "RendererCancelledError",
    "RendererClient",
    "RendererClientError",
    "RendererCommandRunner",
    "RendererOptions",
    "RendererOutputError",
    "RendererRuntimeError",
    "RendererRuntimePins",
    "RendererTimeoutError",
    "RouterMediaClient",
    "RuntimeGenerationMediaClient",
    "SourceSpec",
    "StageStatus",
    "SubprocessCommandRunner",
    "SubprocessRendererClient",
    "WindowsFallbackMediaClient",
    "WindowsNarrationAdapter",
    "create_production_renderer_client",
    "default_local_media_client",
    "request_from_desktop",
    "request_from_fixture",
]
