"""Local model catalog, installation, health, hardware and scheduling APIs."""

from .catalog import BUILTIN_CATALOG, CompatibilityReport, ModelCatalog, ModelCatalogEntry
from .domain import (
    ArtifactSpec,
    Capability,
    Ed25519KeyringVerifier,
    ModelManifest,
    RecordingSignatureVerifier,
    ResourceEstimate,
    SerializationFormat,
    SignatureEnvelope,
    SignatureVerifier,
)
from .download import Downloader, DownloadRequest, DownloadResult, HttpRangeDownloader
from .errors import (
    DownloadError,
    InstallError,
    IntegrityError,
    LicenseNotAcceptedError,
    ManifestError,
    ModelInUseError,
    ModelNotInstalledError,
    ModelRuntimeError,
    NetworkDisabledError,
    NetworkPolicyError,
    ResourceUnavailableError,
    SignatureError,
    UnsafeModelError,
)
from .hardware import (
    AmdRocmProbe,
    AppleMetalProbe,
    CommandResult,
    ComputeBackend,
    ComputeDevice,
    HardwareInventory,
    HardwareProbe,
    NvidiaSmiProbe,
    SystemHardwareProbe,
)
from .manager import (
    CapabilityHealthReport,
    CapabilityHealthState,
    HealthState,
    InstalledModel,
    LicenseAcceptance,
    ModelHealthReport,
    ModelManager,
)
from .policy import (
    ExecutionMode,
    ModelTrustPolicy,
    NetworkPolicy,
    NetworkPurpose,
)
from .scheduler import (
    LeaseRequest,
    LeaseSnapshot,
    ResourceLease,
    ResourcePolicy,
    ResourceScheduler,
)

__all__ = [
    "BUILTIN_CATALOG",
    "AmdRocmProbe",
    "AppleMetalProbe",
    "ArtifactSpec",
    "Capability",
    "CapabilityHealthReport",
    "CapabilityHealthState",
    "CommandResult",
    "CompatibilityReport",
    "ComputeBackend",
    "ComputeDevice",
    "DownloadError",
    "DownloadRequest",
    "DownloadResult",
    "Downloader",
    "Ed25519KeyringVerifier",
    "ExecutionMode",
    "HardwareInventory",
    "HardwareProbe",
    "HealthState",
    "HttpRangeDownloader",
    "InstallError",
    "InstalledModel",
    "IntegrityError",
    "LeaseRequest",
    "LeaseSnapshot",
    "LicenseAcceptance",
    "LicenseNotAcceptedError",
    "ManifestError",
    "ModelCatalog",
    "ModelCatalogEntry",
    "ModelHealthReport",
    "ModelInUseError",
    "ModelManager",
    "ModelManifest",
    "ModelNotInstalledError",
    "ModelRuntimeError",
    "ModelTrustPolicy",
    "NetworkDisabledError",
    "NetworkPolicy",
    "NetworkPolicyError",
    "NetworkPurpose",
    "NvidiaSmiProbe",
    "RecordingSignatureVerifier",
    "ResourceEstimate",
    "ResourceLease",
    "ResourcePolicy",
    "ResourceScheduler",
    "ResourceUnavailableError",
    "SerializationFormat",
    "SignatureEnvelope",
    "SignatureError",
    "SignatureVerifier",
    "SystemHardwareProbe",
    "UnsafeModelError",
]
