import type { CreativeConfiguration } from "../types";

export const DEFAULT_CREATIVE_CONFIGURATION: CreativeConfiguration = {
  slide: {
    mode: "designed",
    layoutSystem: "editorial-grid",
    density: "balanced",
    alignmentGuides: true,
    safeAreas: true,
    visualReviewModel: "Choose a vision model",
    patchLimit: 3,
    imageModel: "tutorial-route",
    prompt: "Calm, text-free educational background with clear central negative space for the lesson content",
    loras: [],
    controlAdapter: "None",
    referenceStrength: 55,
    seed: 1842,
    inpaintEnabled: false,
    upscaleModel: "None",
  },
  presenter: {
    workflow: "guided",
    baseModel: "tutorial-route",
    style: "Editorial portrait",
    prompt: "Friendly adult educator, direct eye contact, calm confident expression, clean silhouette, mouth unobstructed",
    negativePrompt: "text, watermark, child, celebrity, occluded mouth, cropped chin, distorted face",
    loras: [],
    seed: 1842,
    controlAdapter: "None",
    referenceImageEnabled: false,
    faceDetailer: false,
    inpaintEnabled: false,
    upscaleModel: "None",
    provenanceRequired: true,
  },
};
