import type { AppSnapshot, ProjectRecord, Scene, SourceRecord } from "./types";

export const karatsubaScenes: Scene[] = [
  {
    id: "scene-hook",
    index: 1,
    title: "One multiplication disappears",
    kind: "title",
    duration: 24,
    narration: "Multiplying two long numbers seems to demand four smaller multiplications. Karatsuba found a way to make one of them disappear.",
    objective: "Create curiosity around the three-product insight",
    status: "approved",
    visual: "thread",
    citations: 2,
    locked: true,
  },
  {
    id: "scene-split",
    index: 2,
    title: "Split each number in half",
    kind: "definition",
    duration: 52,
    narration: "Write x as a times the base plus b, and y as c times the base plus d. This turns one large problem into four familiar smaller products.",
    objective: "Represent both operands as high and low halves",
    status: "approved",
    visual: "split",
    citations: 1,
    locked: false,
  },
  {
    id: "scene-naive",
    index: 3,
    title: "The four-product baseline",
    kind: "diagram",
    duration: 68,
    narration: "Expanding the expression gives ac, ad, bc, and bd. The cross terms are where Karatsuba makes the saving.",
    objective: "Establish the baseline recurrence",
    status: "approved",
    visual: "formula",
    citations: 2,
    locked: false,
  },
  {
    id: "scene-insight",
    index: 4,
    title: "Recover two terms from one product",
    kind: "worked-example",
    duration: 94,
    narration: "Multiply a plus b by c plus d. Subtract ac and bd, and the remainder is exactly ad plus bc. Four products become three.",
    objective: "Derive the Karatsuba identity",
    status: "attention",
    visual: "formula",
    citations: 3,
    locked: false,
  },
  {
    id: "scene-example",
    index: 5,
    title: "Work through 1234 × 5678",
    kind: "worked-example",
    duration: 188,
    narration: "Split at two digits. A is twelve, b is thirty-four, c is fifty-six, and d is seventy-eight. Now compute the three products and reassemble them by place value.",
    objective: "Apply the algorithm to a concrete multiplication",
    status: "draft",
    visual: "formula",
    citations: 1,
    locked: false,
  },
  {
    id: "scene-complexity",
    index: 6,
    title: "Why three beats four",
    kind: "comparison",
    duration: 88,
    narration: "The school method creates four half-size problems. Karatsuba creates three. Repeating that change moves the exponent from two to about one point five eight five.",
    objective: "Compare the asymptotic recurrences",
    status: "draft",
    visual: "split",
    citations: 4,
    locked: false,
  },
  {
    id: "scene-code",
    index: 7,
    title: "Trace a compact implementation",
    kind: "code",
    duration: 126,
    narration: "The base case uses ordinary multiplication. Every recursive call works on shorter operands, and the three results are shifted back into place.",
    objective: "Connect the derivation to executable code",
    status: "draft",
    visual: "code",
    citations: 1,
    locked: false,
  },
  {
    id: "scene-recap",
    index: 8,
    title: "The idea, threaded together",
    kind: "recap",
    duration: 72,
    narration: "Split, compute three products, recover the middle terms, and combine. That single substitution is the heart of Karatsuba multiplication.",
    objective: "Consolidate the mental model",
    status: "draft",
    visual: "summary",
    citations: 2,
    locked: false,
  },
];

export const sources: SourceRecord[] = [
  { id: "src-1", title: "Multiplication of Multidigit Numbers on Automata", origin: "Soviet Physics Doklady · 1962", kind: "paper", license: "Citation only", evidence: 9, status: "verified" },
  { id: "src-2", title: "Introduction to Algorithms, 4th edition", origin: "Cormen, Leiserson, Rivest, Stein", kind: "book", license: "Link only", evidence: 11, status: "verified" },
  { id: "src-3", title: "Karatsuba multiplication", origin: "cp-algorithms.com", kind: "web", license: "CC BY-SA 4.0", evidence: 6, status: "verified" },
  { id: "src-4", title: "Course notes: divide and conquer", origin: "Imported PDF · 18 pages", kind: "document", license: "Private source", evidence: 14, status: "review" },
];

export const projects: ProjectRecord[] = [
  {
    id: "karatsuba",
    title: "Karatsuba, visually",
    topic: "Karatsuba multiplication",
    description: "A rigorous visual derivation of the three-product multiplication method, built around 1234 × 5678.",
    locale: "English",
    audience: "Undergraduate computer science",
    duration: 12,
    updatedAt: "18 minutes ago",
    progress: 72,
    status: "Ready to review",
    theme: "Precision paper",
    privacy: "Local only",
    scenes: karatsubaScenes,
    sources,
  },
  {
    id: "binary-search",
    title: "Binary search without guessing",
    topic: "Binary search invariants",
    description: "Execution traces that make loop invariants and boundary errors visible.",
    locale: "English",
    audience: "Beginning programmers",
    duration: 8,
    updatedAt: "Yesterday",
    progress: 41,
    status: "Planning",
    theme: "Graphite lab",
    privacy: "Approved cloud",
    scenes: karatsubaScenes.slice(0, 5).map((scene, index) => ({ ...scene, id: `binary-${index}`, title: ["The sorted promise", "Choose the middle", "Discard half", "Trace the bounds", "The off-by-one test"][index] ?? scene.title })),
    sources: sources.slice(0, 2),
  },
  {
    id: "french-revolution",
    title: "A revolution in six turning points",
    topic: "The French Revolution",
    description: "A source-grounded map and timeline for secondary history learners.",
    locale: "Spanish",
    audience: "Secondary history",
    duration: 15,
    updatedAt: "Aug 24",
    progress: 100,
    status: "Complete",
    theme: "Atlas red",
    privacy: "Local only",
    scenes: karatsubaScenes.slice(0, 6).map((scene, index) => ({ ...scene, id: `french-${index}`, title: ["France before 1789", "The Estates", "The Tennis Court Oath", "Storming the Bastille", "Rights and rupture", "The republic emerges"][index] ?? scene.title })),
    sources: sources,
  },
];

export const defaultSnapshot: AppSnapshot = {
  projects,
  recentProjectId: "karatsuba",
  studioMode: "guided",
  version: 12,
  jobs: [
    { id: "job-1", title: "Narration alignment", detail: "Scene 5 · Work through 1234 × 5678", status: "running", progress: 68, eta: "about 1 min", cost: "$0.06" },
    { id: "job-2", title: "Citation support check", detail: "18 externally verifiable claims", status: "queued", progress: 0, eta: "next", cost: "$0.03 max" },
    { id: "job-3", title: "Storyboard snapshot", detail: "Version 12 saved locally", status: "complete", progress: 100 },
  ],
};

export const templates = [
  { name: "Explain a hard idea", category: "Concept", scenes: 8, color: "indigo", description: "Build intuition first, then derive the formal model." },
  { name: "Trace the algorithm", category: "Code", scenes: 9, color: "teal", description: "Move through state, execution, edge cases, and complexity." },
  { name: "Evidence-led history", category: "Humanities", scenes: 11, color: "amber", description: "Anchor a timeline in primary and scholarly sources." },
  { name: "Worked derivation", category: "Mathematics", scenes: 7, color: "rose", description: "Turn each symbolic step into a visual transition." },
  { name: "Quick product walkthrough", category: "Software", scenes: 6, color: "blue", description: "Combine screen demonstration, callouts, and recap." },
  { name: "Young learner story", category: "Illustrated", scenes: 10, color: "mint", description: "Teach through a consistent analogy and gentle checks." },
];
